# Form implementation generated from reading ui file 'tela05_cadastropdtv02.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Cadastro_pdt(object):
    def setupUi(self, Cadastro_pdt):
        Cadastro_pdt.setObjectName("Cadastro_pdt")
        Cadastro_pdt.resize(796, 600)
        self.centralwidget = QtWidgets.QWidget(parent=Cadastro_pdt)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_6.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"border-radius: 10px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.splitter = QtWidgets.QSplitter(parent=self.frame_6)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Button_sair = QtWidgets.QPushButton(parent=self.splitter)
        self.Button_sair.setMinimumSize(QtCore.QSize(0, 25))
        self.Button_sair.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_sair.setFont(font)
        self.Button_sair.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_sair.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 170, 127);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Button_sair.setObjectName("Button_sair")
        self.horizontalLayout_2.addWidget(self.splitter)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_8.setMinimumSize(QtCore.QSize(114, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(0, 250))
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(60, 0, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(43, 38, 69, 21))
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(9, 75, 103, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_9.setGeometry(QtCore.QRect(28, 111, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_10.setGeometry(QtCore.QRect(53, 146, 60, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_produto = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_produto.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_produto.setStyleSheet("border-radius: 10px;")
        self.lineEdit_produto.setText("")
        self.lineEdit_produto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_produto.setObjectName("lineEdit_produto")
        self.verticalLayout_2.addWidget(self.lineEdit_produto)
        self.lineEdit_5_qtde = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_5_qtde.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5_qtde.setStyleSheet("border-radius: 10px;")
        self.lineEdit_5_qtde.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_5_qtde.setObjectName("lineEdit_5_qtde")
        self.verticalLayout_2.addWidget(self.lineEdit_5_qtde)
        self.lineEdit_6_cod_barra = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_6_cod_barra.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_6_cod_barra.setStyleSheet("border-radius: 10px;")
        self.lineEdit_6_cod_barra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_6_cod_barra.setObjectName("lineEdit_6_cod_barra")
        self.verticalLayout_2.addWidget(self.lineEdit_6_cod_barra)
        self.lineEdit_7_preco_uni = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_7_preco_uni.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_7_preco_uni.setStyleSheet("border-radius: 10px;")
        self.lineEdit_7_preco_uni.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_7_preco_uni.setObjectName("lineEdit_7_preco_uni")
        self.verticalLayout_2.addWidget(self.lineEdit_7_preco_uni)
        self.lineEdit_8_categoria = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_8_categoria.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_8_categoria.setStyleSheet("border-radius: 10px;")
        self.lineEdit_8_categoria.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_8_categoria.setObjectName("lineEdit_8_categoria")
        self.verticalLayout_2.addWidget(self.lineEdit_8_categoria)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(163, 0, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Button_3_voltar = QtWidgets.QPushButton(parent=self.frame_4)
        self.Button_3_voltar.setMinimumSize(QtCore.QSize(100, 25))
        self.Button_3_voltar.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_3_voltar.setFont(font)
        self.Button_3_voltar.setStyleSheet("QPushButton {\n"
"    \n"
"    \n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.Button_3_voltar.setObjectName("Button_3_voltar")
        self.horizontalLayout_4.addWidget(self.Button_3_voltar)
        self.Button_2_salvar = QtWidgets.QPushButton(parent=self.frame_4)
        self.Button_2_salvar.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_2_salvar.setFont(font)
        self.Button_2_salvar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.Button_2_salvar.setObjectName("Button_2_salvar")
        self.horizontalLayout_4.addWidget(self.Button_2_salvar)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayout_6.addWidget(self.frame_2)
        Cadastro_pdt.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cadastro_pdt)
        QtCore.QMetaObject.connectSlotsByName(Cadastro_pdt)

    def retranslateUi(self, Cadastro_pdt):
        _translate = QtCore.QCoreApplication.translate
        Cadastro_pdt.setWindowTitle(_translate("Cadastro_pdt", "MainWindow"))
        self.label_2.setText(_translate("Cadastro_pdt", "          ESTOQUE"))
        self.Button_sair.setText(_translate("Cadastro_pdt", "Sair"))
        self.label_4.setText(_translate("Cadastro_pdt", "Cadastrar Produto"))
        self.label_3.setText(_translate("Cadastro_pdt", "Produto:"))
        self.label_7.setText(_translate("Cadastro_pdt", "Quantidade:"))
        self.label_8.setText(_translate("Cadastro_pdt", "Código de barras:"))
        self.label_9.setText(_translate("Cadastro_pdt", "Preço Unitario:"))
        self.label_10.setText(_translate("Cadastro_pdt", "Categoria:"))
        self.Button_3_voltar.setText(_translate("Cadastro_pdt", "Voltar"))
        self.Button_2_salvar.setText(_translate("Cadastro_pdt", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cadastro_pdt = QtWidgets.QMainWindow()
    ui = Ui_Cadastro_pdt()
    ui.setupUi(Cadastro_pdt)
    Cadastro_pdt.show()
    sys.exit(app.exec())
