# Form implementation generated from reading ui file 'tela01_loginv02.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(640, 485)
        Login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border-radius: 10px;")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(parent=self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_11.setGeometry(QtCore.QRect(80, 0, 20, 20))
        self.label_11.setMinimumSize(QtCore.QSize(0, 0))
        self.label_11.setStyleSheet("image: url(:/newPrefix/OIP (1).jpg);")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("user.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(31, 0, 47, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.lineEdit_usuario = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_usuario.setMinimumSize(QtCore.QSize(250, 30))
        self.lineEdit_usuario.setMaximumSize(QtCore.QSize(260, 16777215))
        self.lineEdit_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.lineEdit_usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_usuario.setPlaceholderText("")
        self.lineEdit_usuario.setObjectName("lineEdit_usuario")
        self.horizontalLayout_6.addWidget(self.lineEdit_usuario)
        spacerItem4 = QtWidgets.QSpacerItem(150, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_6.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(80, 0, 21, 21))
        self.label_13.setStyleSheet("image: url(:/newPrefix/R.png);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("senha.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(40, 0, 41, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.lineEdit_2_senha = QtWidgets.QLineEdit(parent=self.frame_2)
        self.lineEdit_2_senha.setMinimumSize(QtCore.QSize(250, 30))
        self.lineEdit_2_senha.setMaximumSize(QtCore.QSize(260, 16777215))
        self.lineEdit_2_senha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.lineEdit_2_senha.setText("")
        self.lineEdit_2_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2_senha.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_2_senha.setObjectName("lineEdit_2_senha")
        self.horizontalLayout_7.addWidget(self.lineEdit_2_senha)
        spacerItem6 = QtWidgets.QSpacerItem(150, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_mostrasenha = QtWidgets.QCheckBox(parent=self.frame_3)
        self.checkBox_mostrasenha.setObjectName("checkBox_mostrasenha")
        self.gridLayout_3.addWidget(self.checkBox_mostrasenha, 0, 0, 1, 1)
        self.Button_3_redefinir = QtWidgets.QPushButton(parent=self.frame_3)
        self.Button_3_redefinir.setMinimumSize(QtCore.QSize(100, 25))
        self.Button_3_redefinir.setMaximumSize(QtCore.QSize(120, 200))
        self.Button_3_redefinir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_3_redefinir.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 0);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Button_3_redefinir.setObjectName("Button_3_redefinir")
        self.gridLayout_3.addWidget(self.Button_3_redefinir, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.Button_login = QtWidgets.QPushButton(parent=self.frame_4)
        self.Button_login.setMinimumSize(QtCore.QSize(0, 25))
        self.Button_login.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_login.setFont(font)
        self.Button_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_login.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 170, 127);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 255, 0);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.Button_login.setObjectName("Button_login")
        self.gridLayout_4.addWidget(self.Button_login, 0, 2, 1, 1)
        self.Button_2_sair = QtWidgets.QPushButton(parent=self.frame_4)
        self.Button_2_sair.setMinimumSize(QtCore.QSize(0, 25))
        self.Button_2_sair.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_2_sair.setFont(font)
        self.Button_2_sair.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_2_sair.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 170, 127);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Button_2_sair.setObjectName("Button_2_sair")
        self.gridLayout_4.addWidget(self.Button_2_sair, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label_10.setText(_translate("Login", "CHINA CELL"))
        self.label_12.setText(_translate("Login", "Usúario:"))
        self.label_14.setText(_translate("Login", "Senha:"))
        self.checkBox_mostrasenha.setText(_translate("Login", "Mostrar senha"))
        self.Button_3_redefinir.setText(_translate("Login", "Esqueci minha senha!"))
        self.Button_login.setText(_translate("Login", "Login"))
        self.Button_2_sair.setText(_translate("Login", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
