# Form implementation generated from reading ui file 'tela04_verprodv02.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Ver_produto(object):
    def setupUi(self, Ver_produto):
        Ver_produto.setObjectName("Ver_produto")
        Ver_produto.resize(775, 538)
        self.centralwidget = QtWidgets.QWidget(parent=Ver_produto)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setStyleSheet("background-color: rgb(200, 200, 200);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.splitter = QtWidgets.QSplitter(parent=self.frame)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.Button_sair = QtWidgets.QPushButton(parent=self.splitter)
        self.Button_sair.setMinimumSize(QtCore.QSize(0, 25))
        self.Button_sair.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_sair.setFont(font)
        self.Button_sair.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_sair.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 170, 127);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"border: 2px solid;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Button_sair.setObjectName("Button_sair")
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout_5.addWidget(self.frame)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_12_id = QtWidgets.QLabel(parent=self.frame_3)
        self.label_12_id.setMinimumSize(QtCore.QSize(70, 30))
        self.label_12_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12_id.setText("")
        self.label_12_id.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12_id.setObjectName("label_12_id")
        self.horizontalLayout_2.addWidget(self.label_12_id)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_produto = QtWidgets.QLabel(parent=self.frame_3)
        self.label_produto.setMinimumSize(QtCore.QSize(300, 30))
        self.label_produto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_produto.setText("")
        self.label_produto.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_produto.setObjectName("label_produto")
        self.horizontalLayout_2.addWidget(self.label_produto)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.frame_3)
        spacerItem5 = QtWidgets.QSpacerItem(0, 130, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_8.setMinimumSize(QtCore.QSize(114, 0))
        self.frame_8.setMaximumSize(QtCore.QSize(0, 250))
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(40, 0, 69, 21))
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 103, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_9.setGeometry(QtCore.QRect(30, 80, 85, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_10.setGeometry(QtCore.QRect(50, 110, 60, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_5_qtde = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_5_qtde.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5_qtde.setStyleSheet("border-radius: 10px;")
        self.lineEdit_5_qtde.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_5_qtde.setObjectName("lineEdit_5_qtde")
        self.verticalLayout_6.addWidget(self.lineEdit_5_qtde)
        self.lineEdit_6_codbarra = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_6_codbarra.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_6_codbarra.setStyleSheet("border-radius: 10px;")
        self.lineEdit_6_codbarra.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_6_codbarra.setObjectName("lineEdit_6_codbarra")
        self.verticalLayout_6.addWidget(self.lineEdit_6_codbarra)
        self.lineEdit_7_prec_uni = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_7_prec_uni.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_7_prec_uni.setStyleSheet("border-radius: 10px;")
        self.lineEdit_7_prec_uni.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_7_prec_uni.setObjectName("lineEdit_7_prec_uni")
        self.verticalLayout_6.addWidget(self.lineEdit_7_prec_uni)
        self.lineEdit_8_categoria = QtWidgets.QLineEdit(parent=self.frame_5)
        self.lineEdit_8_categoria.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_8_categoria.setStyleSheet("border-radius: 10px;")
        self.lineEdit_8_categoria.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_8_categoria.setObjectName("lineEdit_8_categoria")
        self.verticalLayout_6.addWidget(self.lineEdit_8_categoria)
        self.label_14_preco_total = QtWidgets.QLabel(parent=self.frame_5)
        self.label_14_preco_total.setMinimumSize(QtCore.QSize(30, 30))
        self.label_14_preco_total.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_14_preco_total.setText("")
        self.label_14_preco_total.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14_preco_total.setObjectName("label_14_preco_total")
        self.verticalLayout_6.addWidget(self.label_14_preco_total)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(163, 0, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_3.addWidget(self.frame_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Button_2_deletar = QtWidgets.QPushButton(parent=self.frame_4)
        self.Button_2_deletar.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_2_deletar.setFont(font)
        self.Button_2_deletar.setStyleSheet("QPushButton {\n"
"    \n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.Button_2_deletar.setObjectName("Button_2_deletar")
        self.horizontalLayout_4.addWidget(self.Button_2_deletar)
        self.Button_3_voltar = QtWidgets.QPushButton(parent=self.frame_4)
        self.Button_3_voltar.setMinimumSize(QtCore.QSize(100, 25))
        self.Button_3_voltar.setMaximumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_3_voltar.setFont(font)
        self.Button_3_voltar.setStyleSheet("QPushButton {\n"
"    \n"
"    \n"
"    background-color: rgb(0, 85, 255);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.Button_3_voltar.setObjectName("Button_3_voltar")
        self.horizontalLayout_4.addWidget(self.Button_3_voltar)
        self.Button_4_salvar = QtWidgets.QPushButton(parent=self.frame_4)
        self.Button_4_salvar.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_4_salvar.setFont(font)
        self.Button_4_salvar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.Button_4_salvar.setObjectName("Button_4_salvar")
        self.horizontalLayout_4.addWidget(self.Button_4_salvar)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_5.addWidget(self.frame_2)
        Ver_produto.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ver_produto)
        QtCore.QMetaObject.connectSlotsByName(Ver_produto)

    def retranslateUi(self, Ver_produto):
        _translate = QtCore.QCoreApplication.translate
        Ver_produto.setWindowTitle(_translate("Ver_produto", "MainWindow"))
        self.label.setText(_translate("Ver_produto", "          ESTOQUE"))
        self.Button_sair.setText(_translate("Ver_produto", "Sair"))
        self.label_4.setText(_translate("Ver_produto", "ID:"))
        self.label_2.setText(_translate("Ver_produto", "Produto:"))
        self.label_3.setText(_translate("Ver_produto", "Preço Total:"))
        self.label_7.setText(_translate("Ver_produto", "Quantidade:"))
        self.label_8.setText(_translate("Ver_produto", "Código de barras:"))
        self.label_9.setText(_translate("Ver_produto", "Preço Unitario:"))
        self.label_10.setText(_translate("Ver_produto", "Categoria:"))
        self.Button_2_deletar.setText(_translate("Ver_produto", "Deletar"))
        self.Button_3_voltar.setText(_translate("Ver_produto", "Voltar"))
        self.Button_4_salvar.setText(_translate("Ver_produto", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ver_produto = QtWidgets.QMainWindow()
    ui = Ui_Ver_produto()
    ui.setupUi(Ver_produto)
    Ver_produto.show()
    sys.exit(app.exec())
